### ISSUE TITLE
ERROR: 'SecretStr' object has no attribute 'to_dict'

### ISSUE THREAD

**Issue by kylelaverty** [buildarr/buildarr-radarr#63]
This issue comes up anytime I try to configure a download client in radarr. It also happens if there is an existing client configured of the same type and I would be overriding it.

If it matters, I was trying to configure a qBitTorrent type.

It appears to be related to this issue: https://github.com/OpenAPITools/openapi-generator/issues/16086

```
2024-07-31 14:58:26 2024-07-31 14:58:26,152 buildarr:1 buildarr.cli.daemon [ERROR] <radarr> (default) An error occurred while applying initial configuration: 'SecretStr' object has no attribute 'to_dict'
2024-07-31 14:58:26 Traceback (most recent call last):
2024-07-31 14:58:26   File "/usr/local/lib/python3.11/site-packages/buildarr/cli/daemon.py", line 215, in _initial_run
2024-07-31 14:58:26     run_apply()
2024-07-31 14:58:26   File "/usr/local/lib/python3.11/site-packages/buildarr/cli/run.py", line 248, in _run
2024-07-31 14:58:26     if manager.update_remote(
2024-07-31 14:58:26        ^^^^^^^^^^^^^^^^^^^^^^
2024-07-31 14:58:26   File "/usr/local/lib/python3.11/site-packages/buildarr/manager/__init__.py", line 192, in update_remote
2024-07-31 14:58:26     return local_instance_config.update_remote(
2024-07-31 14:58:26            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-31 14:58:26   File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 272, in update_remote
2024-07-31 14:58:26     if isinstance(field, ConfigBase) and field.update_remote(
2024-07-31 14:58:26                                          ^^^^^^^^^^^^^^^^^^^^
2024-07-31 14:58:26   File "/usr/local/lib/python3.11/site-packages/buildarr_radarr/config/settings/__init__.py", line 91, in update_remote
2024-07-31 14:58:26     self.download_clients.update_remote(
2024-07-31 14:58:26   File "/usr/local/lib/python3.11/site-packages/buildarr_radarr/config/settings/download_clients/__init__.py", line 170, in update_remote
2024-07-31 14:58:26     downloadclient._create_remote(
2024-07-31 14:58:26   File "/usr/local/lib/python3.11/site-packages/buildarr_radarr/config/settings/download_clients/base.py", line 136, in _create_remote
2024-07-31 14:58:26     radarr.DownloadClientApi(api_client).create_download_client(
2024-07-31 14:58:26   File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
2024-07-31 14:58:26   File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
2024-07-31 14:58:26   File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
2024-07-31 14:58:26   File "/usr/local/lib/python3.11/site-packages/radarr/api/download_client_api.py", line 76, in create_download_client
2024-07-31 14:58:26     return self.create_download_client_with_http_info(force_save, download_client_resource, **kwargs)  # noqa: E501
2024-07-31 14:58:26            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-31 14:58:26   File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
2024-07-31 14:58:26   File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
2024-07-31 14:58:26   File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
2024-07-31 14:58:26   File "/usr/local/lib/python3.11/site-packages/radarr/api/download_client_api.py", line 184, in create_download_client_with_http_info
2024-07-31 14:58:26     return self.api_client.call_api(
2024-07-31 14:58:26            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-31 14:58:26   File "/usr/local/lib/python3.11/site-packages/radarr/api_client.py", line 413, in call_api
2024-07-31 14:58:26     return self.__call_api(resource_path, method,
2024-07-31 14:58:26            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-31 14:58:26   File "/usr/local/lib/python3.11/site-packages/radarr/api_client.py", line 200, in __call_api
2024-07-31 14:58:26     body = self.sanitize_for_serialization(body)
2024-07-31 14:58:26            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-31 14:58:26   File "/usr/local/lib/python3.11/site-packages/radarr/api_client.py", line 301, in sanitize_for_serialization
2024-07-31 14:58:26     return {key: self.sanitize_for_serialization(val)
2024-07-31 14:58:26            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-31 14:58:26   File "/usr/local/lib/python3.11/site-packages/radarr/api_client.py", line 301, in <dictcomp>
2024-07-31 14:58:26     return {key: self.sanitize_for_serialization(val)
2024-07-31 14:58:26                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-31 14:58:26   File "/usr/local/lib/python3.11/site-packages/radarr/api_client.py", line 283, in sanitize_for_serialization
2024-07-31 14:58:26     return [self.sanitize_for_serialization(sub_obj)
2024-07-31 14:58:26            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-31 14:58:26   File "/usr/local/lib/python3.11/site-packages/radarr/api_client.py", line 283, in <listcomp>
2024-07-31 14:58:26     return [self.sanitize_for_serialization(sub_obj)
2024-07-31 14:58:26             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-31 14:58:26   File "/usr/local/lib/python3.11/site-packages/radarr/api_client.py", line 301, in sanitize_for_serialization
2024-07-31 14:58:26     return {key: self.sanitize_for_serialization(val)
2024-07-31 14:58:26            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-31 14:58:26   File "/usr/local/lib/python3.11/site-packages/radarr/api_client.py", line 301, in <dictcomp>
2024-07-31 14:58:26     return {key: self.sanitize_for_serialization(val)
2024-07-31 14:58:26                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-31 14:58:26   File "/usr/local/lib/python3.11/site-packages/radarr/api_client.py", line 299, in sanitize_for_serialization
2024-07-31 14:58:26     obj_dict = obj.to_dict()
2024-07-31 14:58:26                ^^^^^^^^^^^
2024-07-31 14:58:26 AttributeError: 'SecretStr' object has no attribute 'to_dict'
```

**Comment by s-amberg** [comment]
Had the same issue. Not using user+password authentication for qbittorrent while not optimal, solves this in theory, while not optimal. So my workaround was whitelisting my docker compose subnet in qbittorrent to bypass authentication (or just radarr).
