### ISSUE TITLE
Radarr dump-config error

### ISSUE THREAD

**Issue by GitBurtHET** [buildarr/buildarr-radarr#65]
I am starting to use Buildarr for *arr stack config and want to evaluate it against and combine it with Flemmarr and Configarr to configure the full *arr stack as Code.

For Sonarr, Prowlarr and Jellyseer I was able to succesfully dump their configs.
For Radarr I only change the buildarr subcommand to `radarr` and the URL/port in comparisson to Sonarr, Prowlarr and Jellyseer.

Buildarr command:
```
docker run -it --rm --network media-server_caddy callum027/buildarr:latest radarr dump-config http://radarr:7878
```

Is this an error I can resolve as a user?
Is only a specific Radarr version supported, or do you know what version should be able to work?

Output:
```
Radarr instance API key (or leave blank to auto-fetch): 
Traceback (most recent call last):
  File "/usr/local/bin/buildarr", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr_radarr/cli.py", line 94, in dump_config
    .from_remote(
     ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr/manager/__init__.py", line 171, in from_remote
    return instance_config.from_remote(secrets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr_radarr/config/__init__.py", line 193, in from_remote
    settings=RadarrSettings.from_remote(secrets),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr/config/base.py", line 85, in from_remote
    fields[field_name] = field.type_.from_remote(secrets)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/buildarr_radarr/config/settings/media_management.py", line 432, in from_remote
    api_naming_config = radarr.NamingConfigApi(api_client).get_naming_config()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
  File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
  File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
  File "/usr/local/lib/python3.11/site-packages/radarr/api/naming_config_api.py", line 72, in get_naming_config
    return self.get_naming_config_with_http_info(**kwargs)  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
  File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
  File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
  File "/usr/local/lib/python3.11/site-packages/radarr/api/naming_config_api.py", line 163, in get_naming_config_with_http_info        
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/radarr/api_client.py", line 413, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/radarr/api_client.py", line 254, in __call_api
    return_data = self.deserialize(response_data, response_type)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/radarr/api_client.py", line 324, in deserialize
    return self.__deserialize(data, response_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/radarr/api_client.py", line 363, in __deserialize
    return self.__deserialize_model(data, klass)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/radarr/api_client.py", line 755, in __deserialize_model
    return klass.from_dict(data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/radarr/models/naming_config_resource.py", line 96, in from_dict
    _obj = NamingConfigResource.parse_obj({
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for NamingConfigResource
colonReplacementFormat
  value is not a valid enumeration member; permitted: 'delete', 'dash', 'spaceDash', 'spaceDashSpace' (type=type_error.enum; enum_values=[<ColonReplacementFormat.DELETE: 'delete'>, <ColonReplacementFormat.DASH: 'dash'>, <ColonReplacementFormat.SPACEDASH: 'spaceDash'>, <ColonReplacementFormat.SPACEDASHSPACE: 'spaceDashSpace'>])
 ```

**Comment by Killian-G** [comment]
I got the same error, it is related to the version of radarr-py package which is outdated, and does not include the value `smart` for `colonReplacementFormat`, I have found a workaround: In Radarr go to Settings -> Media Management, if it not the case check `Replace Illegal Characters`, change `Colon Replacement` to any value other than `smart`, you can then uncheck `Replace Illegal Characters` and it will fix the error
